@startuml
left to right direction
actor "Usuário Não Autenticado" as UGuest
actor "Usuário Autenticado" as UAuth

package "Gerenciamento de Autenticação" {
    UGuest --> (Login)
    UGuest --> (Cadastrar Usuário)
    UGuest --> (Recuperar Senha)
    UAuth --> (Logout)
}

package "Gerenciamento do Sistema" {
    UAuth --> (Gerenciar Cômodos)
    UAuth --> (Gerenciar Dispositivos)
    UAuth --> (Gerenciar Cenas)
}

package "Gerenciar Cômodos" {
    (Gerenciar Cômodos) .> (Criar Cômodo) : includes
    (Gerenciar Cômodos) .> (Visualizar Cômodos) : includes
    (Gerenciar Cômodos) .> (Remover Cômodo) : includes
}

package "Gerenciar Dispositivos" {
    (Gerenciar Dispositivos) .> (Criar Dispositivo) : includes
    (Gerenciar Dispositivos) .> (Editar Dispositivo) : includes
    (Gerenciar Dispositivos) .> (Alternar Estado) : includes
    (Gerenciar Dispositivos) .> (Remover Dispositivo) : includes
}

package "Gerenciar Cenas" {
    (Gerenciar Cenas) .> (Criar Cena) : includes
    (Gerenciar Cenas) .> (Editar Cena) : includes
    (Gerenciar Cenas) .> (Remover Cena) : includes
    (Gerenciar Cenas) .> (Executar Cena) : includes
}

@enduml